apiVersion: v1
appVersion: v1.1.1
name: k8s-replicator
description: Controller for replicating secrets and configMaps across namespaces, and help with randomly generated passwords deployed with helm
version: 1.1.1
url: https://github.com/olli-ai/k8s-replicator
