apiVersion: v1
appVersion: v0.0.6
name: k8s-replicator
description: Controller for replicating secrets and configmaps across namespaces, and help with randomly generated password deployed with helm
version: 0.0.6
url: https://github.com/olli-ai/k8s-replicator
